[package]
name = "google-keep"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wry = { git = "https://github.com/tauri-apps/wry" }